name: Heraldex Build
on:
  push:
jobs:
  copyfile:
    runs-on: ubuntu-latest
    paths:
      - 'src/heraldex.js'
    steps:
      - name: Copy heraldex.js to examples
        run:  |
          cp src/heraldex.js example/Timedex/heraldex.js
